<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Buku extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Buku_model');
    } 

    /*
     * Listing of buku
     */
    function index()
    {
        $data['buku'] = $this->Buku_model->get_all_buku();
        
        $data['_view'] = 'buku/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new buku
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_kategori' => $this->input->post('id_kategori'),
				'judul' => $this->input->post('judul'),
				'harga' => $this->input->post('harga'),
				'stok' => $this->input->post('stok'),
				'penerbit' => $this->input->post('penerbit'),
				'deskripsi' => $this->input->post('deskripsi'),
            );
            
            $buku_id = $this->Buku_model->add_buku($params);
            redirect('buku/index');
        }
        else
        {            
            $data['_view'] = 'buku/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a buku
     */
    function edit($id_buku)
    {   
        // check if the buku exists before trying to edit it
        $data['buku'] = $this->Buku_model->get_buku($id_buku);
        
        if(isset($data['buku']['id_buku']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_kategori' => $this->input->post('id_kategori'),
					'judul' => $this->input->post('judul'),
					'harga' => $this->input->post('harga'),
					'stok' => $this->input->post('stok'),
					'penerbit' => $this->input->post('penerbit'),
					'deskripsi' => $this->input->post('deskripsi'),
                );

                $this->Buku_model->update_buku($id_buku,$params);            
                redirect('buku/index');
            }
            else
            {
                $data['_view'] = 'buku/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The buku you are trying to edit does not exist.');
    } 

    /*
     * Deleting buku
     */
    function remove($id_buku)
    {
        $buku = $this->Buku_model->get_buku($id_buku);

        // check if the buku exists before trying to delete it
        if(isset($buku['id_buku']))
        {
            $this->Buku_model->delete_buku($id_buku);
            redirect('buku/index');
        }
        else
            show_error('The buku you are trying to delete does not exist.');
    }
    
}
