<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategori extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kategori_model');
    } 

    /*
     * Listing of kategori
     */
    function index()
    {
        $data['kategori'] = $this->Kategori_model->get_all_kategori();
        
        $data['_view'] = 'kategori/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kategori
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_kategori' => $this->input->post('nama_kategori'),
            );
            
            $kategori_id = $this->Kategori_model->add_kategori($params);
            redirect('kategori/index');
        }
        else
        {            
            $data['_view'] = 'kategori/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kategori
     */
    function edit($id_kategori)
    {   
        // check if the kategori exists before trying to edit it
        $data['kategori'] = $this->Kategori_model->get_kategori($id_kategori);
        
        if(isset($data['kategori']['id_kategori']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_kategori' => $this->input->post('nama_kategori'),
                );

                $this->Kategori_model->update_kategori($id_kategori,$params);            
                redirect('kategori/index');
            }
            else
            {
                $data['_view'] = 'kategori/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kategori you are trying to edit does not exist.');
    } 

    /*
     * Deleting kategori
     */
    function remove($id_kategori)
    {
        $kategori = $this->Kategori_model->get_kategori($id_kategori);

        // check if the kategori exists before trying to delete it
        if(isset($kategori['id_kategori']))
        {
            $this->Kategori_model->delete_kategori($id_kategori);
            redirect('kategori/index');
        }
        else
            show_error('The kategori you are trying to delete does not exist.');
    }
    
}
