<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Buku_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get buku by id_buku
     */
    function get_buku($id_buku)
    {
        return $this->db->get_where('buku',array('id_buku'=>$id_buku))->row_array();
    }
        
    /*
     * Get all buku
     */
    function get_all_buku()
    {
        $this->db->order_by('id_buku', 'desc');
        return $this->db->get('buku')->result_array();
    }
        
    /*
     * function to add new buku
     */
    function add_buku($params)
    {
        $this->db->insert('buku',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update buku
     */
    function update_buku($id_buku,$params)
    {
        $this->db->where('id_buku',$id_buku);
        return $this->db->update('buku',$params);
    }
    
    /*
     * function to delete buku
     */
    function delete_buku($id_buku)
    {
        return $this->db->delete('buku',array('id_buku'=>$id_buku));
    }
}
